### ISSUE TITLE
Investment financing

### ISSUE THREAD

**Issue by codykallen** [PSLmodels/Cost-of-Capital-Calculator#173]
Currently, B-Tax assumes that 32% of marginal corporate investment is financed with debt, and 29% of noncorporate investment. Is there an effort to modify this to apply different financing mixes by industry or asset type? If not, I think it would be reasonable to change these financing assumptions to user-defined parameters, such as `btax_econ_financing_nc` (default value of 0.29) and `btax_econ_financing_c` (default value of 0.32). This would allow a user to observe what happens if a partial limitation on the deductability of net interest is applied, with assumptions about the response of firm borrowing to a reduction in firm debt. 

It would also be useful to separate the haircut on the interest deduction `btax_other_hair` into one for corporate debt and one for noncorporate debt. Although such a proposal would be obviously open to exploitation by tax planners, I believe it is useful to model this, given that the recent tax proposal outline applies the NID limitation only to corporate debt. 

If anyone has suggestions on these, please let me know. If you think these changes are worthwhile, I can open a PR to implement them. 

@MattHJensen @jdebacker

**Comment by jdebacker** [comment]
> Is there an effort to modify this to apply different financing mixes by industry or asset type?

There was, but little progress has been made on this in the last 12 months.  If you are interested in pursuing this, I'll share what notes/scripts/data I have.  I think it's a worthwhile addition.

> If not, I think it would be reasonable to change these financing assumptions to user-defined parameters, such as btax_econ_financing_nc (default value of 0.29) and btax_econ_financing_c (default value of 0.32). This would allow a user to observe what happens if a partial limitation on the deductability of net interest is applied, with assumptions about the response of firm borrowing to a reduction in firm debt.

My preference for this would be to determine some behavioral parameter - e.g., an elasticity of debt financing w.r.t. the the wedge between the cost of capital for debt and equity financed investment -  and then apply this to the B-Tax results in a way that is analogous to the dynamic simulations in TaxBrain.  My reasoning here is:
* It would be difficult to guess how the ratio of debt and equity financing would change as a result of any  given proposal.  Rather,  if you have a policy invariant parameter, like an elasticity, then you could apply this to any policy change.
* If the user defines the ratio, that would make the current results tables seem odd.  It would no longer be "typically financed" investment (i.e., based on the historical debt/equity ratios), but rather some "user defined financed" investment.  And given that the equity and debt financed results are already reported, one could already construct a pretty close measure by taking a weighed average of these two without much effort (where the user would be free to choose their weights).
* Using the elasticity and having a dynamic results module would allow one to compare the changes with and without behavioral responses and to see how financial policies would change.

> It would also be useful to separate the haircut on the interest deduction btax_other_hair into one for corporate debt and one for noncorporate debt. 

I agree.  And actually, it might be nice to allow all the parameters to vary across corporate/non-corporate entities.

>

**Comment by codykallen** [comment]
> And given that the equity and debt financed results are already reported, one could already construct a pretty close measure by taking a weighed average of these two without much effort (where the user would be free to choose their weights).

Unfortunately, it is more difficult to determine the weights that make the "typically financed" METR a weighted average of the debt-financed and equity-financed METRs, since the weights of the historical debt-equity mix don't work for that. For example, the corporate METRs on autos are 9.4% for the typically financed investment, -55.7% for a debt-financed investment, and 21.2% for an equity-financed investment. Weighting the debt and equity METRs by the typical financing mix produces a weighted average of -3.4%. I'm not convinced that taking a weighted average is the right approach. 

> It would be difficult to guess how the ratio of debt and equity financing would change as a result of any given proposal. Rather, if you have a policy invariant parameter, like an elasticity, then you could apply this to any policy change.

I agree that it isn't easy to guess how the financing mix would change, but an elasticity is useful only for tax policies that produce marginal changes; an elasticity can produce impossible or implausible results when applied to bounded variables. For example, eliminating the interest deduction and applying an elasticity to the debt financing share could produce a negative debt financing share of the "typically financed" investment.

**Comment by jdebacker** [comment]
> I'm not convinced that taking a weighted average is the right approach.

It's certainly not right, but I thought it'd get one in the ballpark.  But your example is good one to show this is in not necessarily the case.

> I agree that it isn't easy to guess how the financing mix would change, but an elasticity is useful only for tax policies that produce marginal changes; an elasticity can produce impossible or implausible results when applied to bounded variables. For example, eliminating the interest deduction and applying an elasticity to the debt financing share could produce a negative debt financing share of the "typically financed" investment.

I still favor the elasticity approach.  One can obviously put bounds on this so the results are not infeasible.  There are limitations from not modeling the full behavioral response and deep parameters of the model that are summarized with the elasticity.  For bigger reforms we need a structural model of corporate financial decisions to be more accurate.  But even with large reforms, I like the information the elasticity provides rather than having the user guess.

Although let me caveat all this by saying that what I'm saying mostly applies to CCC where the user might be less experienced and where we have less flexibility in how results are displayed.  For B-Tax itself, I think we might as well make it as easy as possible to change all the assumptions.  Currently, all parameters of the model that can't be adjusted on CCC (with a couple exceptions, including Tax-Calc reforms) are hardcoded into `parameters.py`.  At the time of development, I didn't know much better.  What we should probably do is have all the model parameters in JSON files - maybe splitting up between tax policy parameters (which are already mostly in their own JSON) and "behavioral" parameters (this would include the debt-equity split, fraction of inventories using LIFO, fraction of capital gains not realized before death, etc).  Users could then edit their own JSON to run with whatever parameters they wish.

**Comment by jdebacker** [comment]
Opened two issues (Issue #248 and Issue #249) to note the requests made here.
