### ISSUE TITLE
Odd results when changing investment taxes

### ISSUE THREAD

**Issue by codykallen** [PSLmodels/Cost-of-Capital-Calculator#177]
Generally, an intuitive approach would assume that reducing investment taxes (such as the rate on long-term capital gains and qualified dividends, or repealing the NIIT) would decrease the cost of capital for C corporations (by reducing their financing costs) but would not have a direct effect on the pass-through cost of capital. 

However, the results using B-Tax show that reducing investment taxes (by setting `'_CG_rt3': [0.15], '_NIIT_rt': [0.0]` has no effect on the cost of capital for C corporations, and it increases the cost of capital for non-corporations. This is attributable to the assumptions involved in B-Tax, where `i` and `E_c` are hardcoded, and `E_nc` is calculated based on the after-tax return to equity-holders `s_c_e` (based on the assumption that after-tax returns to the owners of equity should be equal across legal firm status. 

Hence when the tax rate on income from equity decreases, the required rate of return on corporate equity `E_c` does not change, but the after-tax return on investing in corporate equity `s_c_e` increases, which also increases the required rate of return on non-corporate equity `E_nc`. 

This has serious and problematic implications. For example, suppose you proposed to reduce taxes on income from corporate equity, and wanted to apply an investment response based on the user cost of capital. Because of the assumptions used to determine `E_c` and `E_nc`, such a response would show no change in corporate investment and a decrease in non-corporate investment, when it should show an increase in corporate investment and no change in non-corporate investment.

**Comment by jdebacker** [comment]
This is interesting and I agree could be non-intuitive.  I might, however, disagree with

> ...when it should show an increase in corporate investment and no change in non-corporate investment.

Many (thought not all) measures of the cost of capital user the Hall-Jorgenson user cost of capital formulation and exclude personal  income tax rates (see [CBO](https://www.cbo.gov/sites/default/files/113th-congress-2013-2014/reports/49817-taxingcapitalincome0.pdf), [Treasury](https://www.treasury.gov/resource-center/tax-policy/tax-analysis/Documents/New-Investment-Rates-Methodology.pdf), and Cummins Hassett, and Hubbard (1994)).  In this context, changes in individual taxes should not affect the user cost of capital for corporations (though they will affect the METTR and so should affect investment incentives via that channel).  Others, such as [Gale and Orzag (2005)](https://www.brookings.edu/wp-content/uploads/2016/06/20050721galeorszag.pdf) do allow individual tax rates to factor into the cost of capital.  But these models are the exception and so I don't know if there are as many estimates of the elasticity of investment with respect to the cost of capital that are measured this way (and you do want to be careful in applying an elasticity that is measured with respect to the same formulation of the cost of capital).

The non-corporate result is more still more unintuitive.  But I don't know that it's wrong.  The Hall-Jorgenson user cost of capital and the METRs based on them are equilibrium concepts.  An important component of this is that rates of returns are equalized.  In this context, a higher after-tax rate of return on corporate investments would indeed lead to a decrease in non-corporate investments.  That said, I could see alternative assumptions here and I agree that the user cost of capital and METRs for non-corporate investments do require careful interpretation (e.g., there have been questions about results when an entity level taxes is placed on non-corporate entities since the METR needs to be redefined for those businesses in that case).

My suggestions for handling this would be:
* Leave the cost of capital calculation for corporations as is (to be consistent with most others' views of it).
* Consider changing the required pre-tax rate of return required for non-corporate businesses (perhaps allowing for some option such as a default where the after-tax rates of returns are equalized (as now) and one where the required pre-tax rate of return for non-corporate entities is given by the user).
* Find a systematic way to highlight some of the non-intuitive results to preempt questions and help users understand what they are seeing (this list would include at least what you highlight here, my note above about METRs for non-corporate entities, and 2-3 other questions I've received more than once about the model results).

**Comment by codykallen** [comment]
I agree that it should be fine to not have the tax rates on investment income affect cost of capital, as it's difficult to judge how interest rates may respond to changes in those taxes. But then it is very problematic for changes in taxes on investment income to alter the cost of capital for non-corporate investment. In other words, we are assuming the real return on corporate equity is not sensitive to shareholder-level taxes on equity income, but that the real return on non-corporate equity is sensitive to the shareholder-level taxes on income from corporate equity. 

I think the most straightforward fix would be to calculate the real, after-tax rate of return on equity `s_c_e` under the baseline, and hardcode `E_nc` to be equal to the value of `s_c_e` calculated in the baseline scenario, not the reform scenario. That should resolve the problem.

**Comment by jdebacker** [comment]
> I think the most straightforward fix would be to calculate the real, after-tax rate of return on equity s_c_e under the baseline, and hardcode E_nc to be equal to the value of s_c_e calculated in the baseline scenario, not the reform scenario. That should resolve the problem.

I like this suggestion.

**Comment by jdebacker** [comment]
This still needs to be implemented.  It requires output from the baseline run being used in the reform policy run.  Doing this will require some engineering of how `run_btax.py()` works and and will be left for a major model overhaul that will bring B-Tax up to the PolicyBrain API standards.

**Comment by jdebacker** [comment]
With the new CCC API, one can keep the rate of return constant across runs.  e.g., to keep the required after-tax rate of return on equity-financed pass-through investments the same across two model parameterizations:

```
# import CCC objects
from ccc.data import Assets
from ccc.parameters import Specifications
from ccc.calculator import Calculator
# Create an instance of the assets class
assets = Assets()
# Create an instance of the parameters class
base_params = Specifications()
# Create an instance of the calculator class
base_calc = Calculator(base_params, assets)
# Create another instance of the parameters class
reform_params = Specifications(call_tc=True, iit_reform=some_TC_polciy_dict)
# set required rates of return on equity-financed pass-through investments to those from the baseline
reform_params.s['nc']['e'] = base_params.s['nc'][e']
# Create another instance of the calculator class for the reform
reform_calc = Calculator(reform_params, assets)
```
