### ISSUE TITLE
Interest deductibility haircut for business entities at 0% instead of 30%. 

### ISSUE THREAD

**Issue by MattHJensen** [PSLmodels/Cost-of-Capital-Calculator#285]
The CCC app on Compute Studio shows the interest deductibility haircut under current law in 2019 as 0%. 

![image](https://user-images.githubusercontent.com/8301092/66666428-98e79a80-ec1e-11e9-86a1-863ab99006fe.png)

I would have expected this to be 30% because of TCJA, with some caveats for aspects of the law that aren't modeled. 

https://www.irs.gov/instructions/i8990

Some additional documentation might be helpful if this isn't a bug.

**Comment by jdebacker** [comment]
@MattHJensen The issue here is that the limitation only applies (generally) if the interest deduction exceeds 30% of (adjusted) taxable income.  I don't know of public microdata that would allow one to identify the fraction of firms for whom this is binding.   With such data, I could see computing a weighted average cost-of-capital that reflects the fraction of investments for which the interest limitation applies to.  If you are aware of such data, let me know.

But I take your point that documentation would help.  I can add this to a note in the interest haircut parameter in `default_parameters.json` so that it'll pop-up in the info box on Compute Studio.

**Comment by jdebacker** [comment]
Resolved with PR #290
